### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by icls1337** [cgbur/llama2.zig#1]
Can you add -march=native to llama2.c make runfast? zig enables it by default.
https://godbolt.org/z/1n3bbTafs
Also enable native for rust.

**Comment by cgbur** [comment]
Forgot about that thanks! Oddly enough the single threaded Rust version actually got slower down to 111 pretty consistently. I gave it the benefit of the doubt and left it at my previous measurement of 115 as it was fairly noisy (not the most scientific benchmarking done in the world). I think if the author there made their loops more SIMD friendly there would be large speed wins.

The runfast configuration from llama.c really gained a lot with `march=native`. Looks like theres some work left to be done!

Closed by 0b4cbbc967d0f4021
