### ISSUE TITLE
utf8 input breaks stuff

### ISSUE THREAD

**Issue by twobob** [cgbur/llama2.zig#5]
main.exe ../out/model15M.bin -t 0 -v -s 42  -i "Værså ran"
config: main.Config{ .dim = 288, .hidden_dim = 768, .n_layers = 6, .n_heads = 6, .n_kv_heads = 6, .vocab_size = 32000, .seq_len = 256 }
shared weights: true
temperature: 0
top-p: 1
SIMD vector size: 4

error: TokenNotFound

 main.exe ../out/model15M.bin -t 0 -v -s 42  -i "Versa ran"
config: main.Config{ .dim = 288, .hidden_dim = 768, .n_layers = 6, .n_heads = 6, .n_kv_heads = 6, .vocab_size = 32000, .seq_len = 256 }
shared weights: true
temperature: 0
top-p: 1
SIMD vector size: 4

Versa ran to the park. et cetera

**Comment by cgbur** [comment]
Done! Thanks for the testing
